[phases]
[phases.setup]
cmds = [
    "npm install --omit=dev",
    "npm install puppeteer --no-save",
    "apt-get update && apt-get install -y libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libxcomposite1 libxrandr2 libxdamage1 libgbm1 libasound2"
]

[start]
cmd = "npm run start:telegram"